const games = [
  {title:"Random Links",folder:"randomlink.html",description:"It's a game that discovers links across the web that you would otherwise never find. Always see something brand new!",developer:"AWEGames",icon:"✈"},
  {title:"Neon Defender",folder:"neondefender.html",description:"Neon Defender Omega is an action-packed space shooter featuring explosive neon visuals, customizable starships, autonomous orbital drones, and intense boss fights. Upgrade your fleet across 100+ market tiers, dominate space waves, and protect the galaxy!",developer:"AWEGames",icon:"✈️🛩️"},
  {title:"⚡ CYBERCORE: CONTROL THE POWER, SURVIVE THE MELTDOWN!",folder:"reactor.html",description:"Harness raw plasma energy, unlock 20+ quantum upgrades, and expand your power grid. Keep your core cool under extreme pressure—or face a total reactor collapse! 🚀",developer:"AWEGames",icon:"☢"},
  {title:"✨ Starlight Meadow ✨",folder:"starlightmeadow.html",description:"Collect stars. Upgrade power. Explore forever. Wander through a breathtaking open meadow as a luminous spirit, gathering starlight in a calm, endless adventure. Earn stars, unlock golden treasures, and supercharge your abilities in the in-game shop. Your journey is always saved — pick up right where you left off, in any of 10 languages.",developer:"AWEGames",icon:"🌲🍀"},
  {title:"Zen Haven",folder:"zenhaven.html",description:"Step into Zen Haven, a breathtaking open-sky sanctuary crafted for peace, mindfulness, and creative freedom. Float through magical islands, plant glowing celestial flora, summon majestic sky wildlife, and create your own tranquil melodies with interactive crystal chimes. Featuring a guided breathing mode, dynamic time-of-day atmospheres, and seamless 10-language support, it is the ultimate interactive retreat right in your browser.",developer:"AWEGames",icon:"🌱🌼🌻"},
  {title:"Aetheria ",folder:"aetheria.html",description:"Aetheria: Endless Zen Sanctuary is a soothing interactive game designed for infinite progression and deep relaxation. It features 50 unique procedural ambient soundscapes, 18 sanctuary upgrades with dynamic inflation economics, and full support for 10 languages. Your complete progress automatically saves directly to your local device, offering a seamless and peaceful sanctuary whenever you need it",developer:"AWEGames",icon:"🔊👆"},
  {title:"Lumina",folder:"lumina.html",description:"Lumina is a serene, endless idle game where you tap a glowing orb to gather light and grow a peaceful garden of companions. Unlock blessings, catch shooting stars for frenzy buffs, earn achievements, and rebirth into stardust for permanent multipliers across eleven languages",developer:"AWEGames",icon:"👆⚫"},
  {title:" Language Garden",folder:"languagegarden.html",description:"A peaceful, endlessly growing idle game where you collect Essence by clicking the sun and unlock over 200 world languages. Each unlocked language automatically generates Essence per second, and you can upgrade their levels to increase production. Every time you unlock a new language, the price of all remaining languages increases by 1%, making the game progressively more challenging. Your progress is automatically saved on your device, so you can continue anytime. A beautiful, calming garden with soft animations, clouds, and sparkles awaits you — grow your language garden forever!",developer:"AWEGames",icon:"🌸"},
  {title:"Nebula Alchemy",folder:"nebulaalchemy.html",description:"Combine cosmic elements like Starlight, Cosmic Dust, and Cosmic Rays in your reactor to synthesize stars, planets, and galaxies. Features 16 unique cosmic elements, recipe discovery tracking, sound effects, and full support for 11 languages.",developer:"AWEGames",icon:"🧪✨"},
  {title:"Cosmic Sudoku",folder:"cosmicsudoku.html",description:"Challenge your mind with Cosmic Sudoku! Featuring procedural starlight logic puzzles, 3 difficulty tiers, hint assistance, error tracking, interactive keypad, and full 11-language support.",developer:"AWEGames",icon:"🧩✨"},
  {title:"Chrono Quest",folder:"chronoquest.html",description:"Master the time loop in Chrono Quest! Battle temporal shadows across infinite floors, harvest Time Echoes, upgrade your hero, and manipulate time in an interactive tactical RPG with 11-language support.",developer:"AWEGames",icon:"⏳⚔️"},
  {title:"⚔️ Cyber Clash P2P",folder:"cyberclash.html",description:"Real-time 2-player P2P tank arena battle featuring WebRTC data sync, live text chat, P2P voice chat, AI bot practice mode, Web Audio effects, and 11-language support!",developer:"AWEGames",icon:"⚔️🎙️"},
  {title:"🪐 Stellar Forge",folder:"stellarforge.html",description:"Build galaxy systems in Stellar Forge! Launch planets, moons, and black holes into orbital equilibrium, harness gravity physics, earn stellar energy, and explore 11 languages.",developer:"AWEGames",icon:"🪐✨"},
  {title:"🃏 Rune Realms",folder:"runerealms.html",description:"A rogue-like elemental card deckbuilder RPG. Channel Fire, Water, Earth, and Air runes, overcome realm guardians, unlock powerful combos, and play across 11 languages.",developer:"AWEGames",icon:"🃏🔥"}
];
(function injectAWEHubNav(){if(document.querySelector('#aweHubNav'))return;const nav=document.querySelector('.nav-links');if(!nav)return;[['AWE A2Z','https://awe-a2z.pages.dev/'],['AWEEXP','https://awe-exp.pages.dev/'],['AWEGame','https://awegame.pages.dev/'],['AWEARCHIVE','https://awearchive.pages.dev/']].forEach(([name,url],i)=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=name;a.className='nav-link';a.id=i===0?'aweHubNav':`aweHub-${i}`;nav.appendChild(a)});})();
