const games = [
  {title:"Random Links",folder:"randomlink.html",description:"It's a game that discovers links across the web that you would otherwise never find. Always see something brand new!",developer:"AWEGames",icon:"✈"},
  {title:"Neon Defender",folder:"neondefender.html",description:"Neon Defender Omega is an action-packed space shooter featuring explosive neon visuals, customizable starships, autonomous orbital drones, and intense boss fights. Upgrade your fleet across 100+ market tiers, dominate space waves, and protect the galaxy!",developer:"AWEGames",icon:"✈️🛩️"},
  {title:"⚡ CYBERCORE: CONTROL THE POWER, SURVIVE THE MELTDOWN!",folder:"reactor.html",description:"Harness raw plasma energy, unlock 20+ quantum upgrades, and expand your power grid. Keep your core cool under extreme pressure—or face a total reactor collapse! 🚀",developer:"AWEGames",icon:"☢"},
  {title:"✨ Starlight Meadow ✨",folder:"starlightmeadow.html",description:"Collect stars. Upgrade power. Explore forever. Wander through a breathtaking open meadow as a luminous spirit, gathering starlight in a calm, endless adventure. Earn stars, unlock golden treasures, and supercharge your abilities in the in-game shop. Your journey is always saved — pick up right where you left off, in any of 10 languages.",developer:"AWEGames",icon:"🌲🍀"},
  {title:"Zen Haven",folder:"zenhaven.html",description:"Step into Zen Haven, a breathtaking open-sky sanctuary crafted for peace, mindfulness, and creative freedom. Float through magical islands, plant glowing celestial flora, summon majestic sky wildlife, and create your own tranquil melodies with interactive crystal chimes. Featuring a guided breathing mode, dynamic time-of-day atmospheres, and seamless 10-language support, it is the ultimate interactive retreat right in your browser.",developer:"AWEGames",icon:"🌱🌼🌻"},
  {title:"Aetheria ",folder:"aetheria.html",description:"Aetheria: Endless Zen Sanctuary is a soothing interactive game designed for infinite progression and deep relaxation. It features 50 unique procedural ambient soundscapes, 18 sanctuary upgrades with dynamic inflation economics, and full support for 10 languages. Your complete progress automatically saves directly to your local device, offering a seamless and peaceful sanctuary whenever you need it",developer:"AWEGames",icon:"🔊👆"},
  {title:"Lumina",folder:"lumina.html",description:"Lumina is a serene, endless idle game where you tap a glowing orb to gather light and grow a peaceful garden of companions. Unlock blessings, catch shooting stars for frenzy buffs, earn achievements, and rebirth into stardust for permanent multipliers across eleven languages",developer:"AWEGames",icon:"👆⚫"},
  {title:" Language Garden",folder:"languagegarden.html",description:"A peaceful, endlessly growing idle game where you collect Essence by clicking the sun and unlock over 200 world languages. Each unlocked language automatically generates Essence per second, and you can upgrade their levels to increase production. Every time you unlock a new language, the price of all remaining languages increases by 1%, making the game progressively more challenging. Your progress is automatically saved on your device, so you can continue anytime. A beautiful, calming garden with soft animations, clouds, and sparkles awaits you — grow your language garden forever!",developer:"AWEGames",icon:"🌸"},
  {title:"Nebula Alchemy",folder:"nebulaalchemy.html",description:"Combine cosmic elements like Starlight, Cosmic Dust, and Cosmic Rays in your reactor to synthesize stars, planets, and galaxies. Features 16 unique cosmic elements, recipe discovery tracking, sound effects, and full support for 11 languages.",developer:"AWEGames",icon:"🧪✨"},
  {title:"Cosmic Sudoku",folder:"cosmicsudoku.html",description:"Challenge your mind with Cosmic Sudoku! Featuring procedural starlight logic puzzles, 3 difficulty tiers, hint assistance, error tracking, interactive keypad, and full 11-language support.",developer:"AWEGames",icon:"🧩✨"},
  {title:"Chrono Quest",folder:"chronoquest.html",description:"Master the time loop in Chrono Quest! Battle temporal shadows across infinite floors, harvest Time Echoes, upgrade your hero, and manipulate time in an interactive tactical RPG with 11-language support.",developer:"AWEGames",icon:"⏳⚔️"},
  {title:"⚔️ Cyber Clash P2P",folder:"cyberclash.html",description:"Real-time 2-player P2P tank arena battle featuring WebRTC data sync, live text chat, P2P voice chat, AI bot practice mode, Web Audio effects, and 11-language support!",developer:"AWEGames",icon:"⚔️🎙️"},
  {title:"🌌 Void Arena P2P",folder:"voidarena.html",description:"Real-time spatial cosmic multiplayer arena featuring WebRTC data sync, live text chat, P2P voice chat with mic visualizer, AI bot practice mode, local storage stats, and 11-language support!",developer:"AWEGames",icon:"🌌🎙️"},
  {title:"🏎️ Cyber Drift Turbo",folder:"cyberdrift.html",description:"High-speed retro synthwave racer with time-warp nitro boosts, incoming traffic dodging, credits collection, high score saving, sound effects, and 11-language support!",developer:"AWEGames",icon:"🏎️⚡"},
  {title:"⌛ Chronos TD: Time Defense",folder:"chronostd.html",description:"Tactical time manipulation Tower Defense! Place Chrono, Laser, and Warp towers, defend your time core across intense waves, collect stars, and play in 11 languages!",developer:"AWEGames",icon:"⌛🛡️"},
  {title:"🪐 Stellar Forge",folder:"stellarforge.html",description:"Build galaxy systems in Stellar Forge! Launch planets, moons, and black holes into orbital equilibrium, harness gravity physics, earn stellar energy, and explore 11 languages.",developer:"AWEGames",icon:"🪐✨"},
  {title:"🃏 Rune Realms",folder:"runerealms.html",description:"A rogue-like elemental card deckbuilder RPG. Channel Fire, Water, Earth, and Air runes, overcome realm guardians, unlock powerful combos, and play across 11 languages.",developer:"AWEGames",icon:"🃏🔥"},
  {title:"🚀 Starship Duel P2P",folder:"starshipduel.html",description:"Sci-fi 2D space dogfight arena featuring WebRTC P2P sync, live text chat, P2P voice chat, AI bot mode, local storage stats, sound synthesis, and 11-language support!",developer:"AWEGames",icon:"🚀🎙️"},
  {title:"🎰 Cosmic Pinball FX",folder:"cosmicpinball.html",description:"Cyberpunk neon arcade pinball with flippers, bumpers, score multiplier upgrades shop, Web Audio sound synthesis, persistent local storage, and 11-language support!",developer:"AWEGames",icon:"🎰✨"},
  {title:"⛏️ Astro Digger RPG",folder:"astrominer.html",description:"Subterranean asteroid drilling and mining RPG with procedural terrain generation, ore selling, surface base upgrades, local storage save system, and 11-language support!",developer:"AWEGames",icon:"⛏️🚀"},
  {title:"🚀 Cosmic Armada P2P",folder:"cosmicarmada.html",description:"Tactical WebRTC P2P fleet arena battle featuring real-time state sync, live text chat, voice chat with mic visualizer, AI bot practice mode, LocalStorage stats, and 11-language support!",developer:"AWEGames",icon:"🚀🎙️"},
  {title:"🪐 Galactic Tycoon",folder:"galactictycoon.html",description:"Sci-Fi planetary mining, refinery building, market trade exchange, base tech research, Web Audio sounds, LocalStorage auto-save, and 11-language support!",developer:"AWEGames",icon:"🪐⚡"},
  {title:"🥷 Shadow Blade Ninja",folder:"shadowblade.html",description:"Action precision platformer featuring katana slashes, shuriken throwing, dojo upgrades shop, enemy ninjas, LocalStorage save system, dynamic touch controls, and 11-language support!",developer:"AWEGames",icon:"🥷🗡️"},
  {title:"🥊 Cyber Brawlers P2P",folder:"cyberbrawlers.html",description:"Action 2D cyberpunk platform brawler arena featuring real-time WebRTC P2P sync, live text chat, P2P voice chat with mic visualizer, AI bot mode, LocalStorage coins saving, and 11-language support!",developer:"AWEGames",icon:"🥊🎙️"},
  {title:"🎵 Neon Rhythm Turbo",folder:"neonrhythm.html",description:"Synthwave rhythm beat action runner with procedural dynamic audio, combo multipliers, high score local storage saving, touch control overlays, and 11-language support!",developer:"AWEGames",icon:"🎵⚡"},
  {title:"🌀 Quantum Maze Hacking",folder:"quantummaze.html",description:"Stealth quantum hacking puzzle game featuring security node extraction, laser sentries, local storage level saving, touch overlays, and 11-language support!",developer:"AWEGames",icon:"🌀🔑"},
  {title:"🏎️ Hyper Hover P2P",folder:"hyperhover.html",description:"High-speed futuristic WebRTC P2P hovercraft racing & arena combat game with real-time state sync, live text chat, voice chat with mic visualizer, AI bot practice mode, LocalStorage credits saving, and 11-language support!",developer:"AWEGames",icon:"🏎️🎙️"},
  {title:"🛡️ Chrono Tactics RPG",folder:"chronotactics.html",description:"Tactical grid turn-based RPG featuring hero skill combos, time gem harvesting, enemy AI combat, LocalStorage stage saving, dynamic touch controls, and 11-language support!",developer:"AWEGames",icon:"🛡️⚔️"},
  {title:"🏰 Cosmic Tower Stacker",folder:"cosmictower.html",description:"Physics precision tower building game featuring stardust collection, high score tracking, LocalStorage saving, responsive fluid layout, dynamic touch overlays, and 11-language support!",developer:"AWEGames",icon:"🏰✨"},
  {title:"🤖 Cyber Mech Duel P2P",folder:"cybermech.html",description:"Futuristic 2D Mech Battle Arena featuring real-time WebRTC P2P sync, live text chat, voice chat with mic visualizer, AI bot practice mode, LocalStorage credits saving, and 11-language support!",developer:"AWEGames",icon:"🤖🎙️"},
  {title:"🧩 Quantum Gravity Blocks",folder:"quantumblox.html",description:"Spatial physics block matching puzzle featuring 4-directional gravity manipulation, combo chain reactions, Web Audio sound effects, LocalStorage high scores, and 11-language support!",developer:"AWEGames",icon:"🧩⚡"},
  {title:"🏰 Cyber Citadel Defense",folder:"cybercitadel.html",description:"Action base defense game featuring central Cyber Citadel wave survival, elemental beam cannons, EMP orbital strikes, tech upgrades shop, LocalStorage crystals saving, and 11-language support!",developer:"AWEGames",icon:"🏰⚡"}
];
(function injectAWEHubNav(){
  if(document.querySelector('#aweHubNav'))return;
  const nav=document.querySelector('.nav-links');if(!nav)return;
  const links=[['A2Z','https://awe-a2z.pages.dev/'],['EXP','https://awe-exp.pages.dev/'],['AWEGame','https://awegame.pages.dev/'],['AWELib','https://awelib.pages.dev/']];
  const style=document.createElement('style');style.textContent=`#aweHubNav,#aweHubNav~a{position:relative;overflow:hidden;border-radius:999px;padding:9px 12px;transition:transform .35s cubic-bezier(.2,.8,.2,1),color .3s,background .3s,box-shadow .3s;animation:aweNavIn .65s cubic-bezier(.2,.8,.2,1) both}#aweHubNav::before,#aweHubNav~a::before{content:"";position:absolute;inset:-60%;background:radial-gradient(circle,#fff8,transparent 52%);opacity:0;transform:scale(.5);transition:.4s;pointer-events:none}#aweHubNav::after,#aweHubNav~a::after{content:"";position:absolute;left:18%;right:18%;bottom:3px;height:2px;border-radius:99px;background:linear-gradient(90deg,#20c8ff,#8b6cff,#d66cff);transform:scaleX(0);transition:.35s}#aweHubNav:hover,#aweHubNav~a:hover{transform:translateY(-3px) scale(1.025);color:#7657e8;background:#ffffff24;box-shadow:0 12px 30px #7657e82b}#aweHubNav:hover::before,#aweHubNav~a:hover::before{opacity:1;transform:scale(1)}#aweHubNav:hover::after,#aweHubNav~a:hover::after{transform:scaleX(1)}@keyframes aweNavIn{from{opacity:0;transform:translateY(-12px) scale(.94);filter:blur(4px)}to{opacity:1;transform:none;filter:none}}`;document.head.appendChild(style);
  links.forEach(([name,url],i)=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=name;a.className='nav-link';a.id=i===0?'aweHubNav':`aweHub-${i}`;a.style.animationDelay=`${i*85}ms`;nav.appendChild(a)});
})();
